name: Unit Tests CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Job 1: Build Job
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build project
        run: echo "Build project"


  # Job 2: Test Job
  test:
    runs-on: ubuntu-latest
    needs: build # This ensures the 'test' job runs only after the 'build' job is successful

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

    
      # Step 4: Run tests
      - name: Run tests
        run: npm test